// scad.js — Port of bottlecap.py SCAD generation to JavaScript

/**
 * Derive cap geometry values from user measurements.
 */
export function computeCap(p, clearance) {
    const bore_r = p.od / 2.0 + clearance / 2.0;
    const lead = p.pitch * p.starts;
    const outer_r = bore_r + p.depth + p.wall;
    const engage_h = p.turns * lead + p.pitch;

    return {
        label: p.label,
        bore_r,
        outer_r,
        lead,
        engage_h,
        pitch: p.pitch,
        starts: p.starts,
        depth: p.depth,
        thread_width: p.threadWidth,
    };
}

/**
 * Cross-validate pitch against thread width + valley width.
 * Returns { pitch, warning }.
 */
export function validatePitch(measuredPitch, threadWidth, valleyWidth) {
    const derived = threadWidth + valleyWidth;
    const pitch = (measuredPitch + derived) / 2.0;
    const diff = Math.abs(measuredPitch - derived);

    let warning = null;
    if (diff > 0.5) {
        warning = `Pitch (${measuredPitch.toFixed(2)}) doesn't match thread + valley `
            + `(${threadWidth.toFixed(2)} + ${valleyWidth.toFixed(2)} = ${derived.toFixed(2)}). `
            + `Using average: ${pitch.toFixed(2)} mm.`;
    }

    return { pitch, warning };
}

/**
 * Generate OpenSCAD source code for the adapter.
 */
export function generateScad(bottleA, bottleB, clearance = 0.3, connectorH = 8.0) {
    const ca = computeCap(bottleA, clearance);
    const cb = computeCap(bottleB, clearance);

    const conn_r = Math.max(ca.outer_r, cb.outer_r);
    const flow_r = Math.min(ca.bore_r, cb.bore_r);
    const a_cap_h = ca.engage_h + 2.0;
    const b_cap_h = cb.engage_h + 2.0;
    const total_h = a_cap_h + connectorH + b_cap_h;

    const fmt = (v) => v.toFixed(4);

    return `// ============================================================
// Bottle Cap Adapter
// ${ca.label}  <->  ${cb.label}
// Generated by BottleCap Web App
//
// Total height : ${total_h.toFixed(1)} mm
// Cap A OD     : ${fmt(ca.outer_r * 2)} mm  (opening at BOTTOM)
// Cap B OD     : ${fmt(cb.outer_r * 2)} mm  (opening at TOP)
// Clearance    : ${clearance} mm (diametral)
//
// Print notes  : No special orientation needed -- the model already
//   sits flat.  Enable auto-supports in Bambu Studio for the upper
//   cap bore overhang.  0.2 mm layer height recommended.
// ============================================================

$fn = 120;   // facet count for cylinders

// -- Cap A  (${ca.label})
A_bore_r       = ${fmt(ca.bore_r)};   // inner bore radius (valley)
A_outer_r      = ${fmt(ca.outer_r)};   // outer cap radius
A_lead         = ${fmt(ca.lead)};   // axial advance per revolution
A_pitch        = ${fmt(ca.pitch)};
A_starts       = ${ca.starts};
A_depth        = ${fmt(ca.depth)};   // thread depth (radial)
A_thread_width = ${fmt(ca.thread_width)};   // axial width of thread ridge
A_engage_h     = ${fmt(ca.engage_h)};   // threaded zone height
A_cap_h        = ${fmt(a_cap_h)};   // total cap height

// -- Cap B  (${cb.label})
B_bore_r       = ${fmt(cb.bore_r)};
B_outer_r      = ${fmt(cb.outer_r)};
B_lead         = ${fmt(cb.lead)};
B_pitch        = ${fmt(cb.pitch)};
B_starts       = ${cb.starts};
B_depth        = ${fmt(cb.depth)};
B_thread_width = ${fmt(cb.thread_width)};
B_engage_h     = ${fmt(cb.engage_h)};
B_cap_h        = ${fmt(b_cap_h)};

// -- Connector
conn_r  = ${fmt(conn_r)};
conn_h  = ${connectorH};
flow_r  = ${fmt(flow_r)};   // flow-through bore radius

// ============================================================
// thread_ridges -- helical ridges on the inside of a bore
//
// Uses hull() of adjacent thin slices along the helix path.
// Each slice is a cube with the exact axial thread_width and
// radial depth, giving precise FDM-printable thread geometry.
// ============================================================
module thread_ridges(bore_r, lead, starts, depth,
                     thread_width, engage_h) {
    segs_per_turn = 72;
    turns = engage_h / lead;
    total_segs = ceil(segs_per_turn * turns);
    wall_overlap = 1.0;  // extend into wall for solid union

    for (s = [0 : starts - 1]) {
        sa = s * 360 / starts;
        for (i = [0 : total_segs - 1]) {
            hull() {
                // Current slice
                rotate([0, 0, sa + i * 360 / segs_per_turn])
                translate([bore_r - depth, -0.01,
                           i * lead / segs_per_turn])
                cube([depth + wall_overlap, 0.02, thread_width]);

                // Next slice
                rotate([0, 0, sa + (i+1) * 360 / segs_per_turn])
                translate([bore_r - depth, -0.01,
                           (i+1) * lead / segs_per_turn])
                cube([depth + wall_overlap, 0.02, thread_width]);
            }
        }
    }
}

// ============================================================
// female_cap -- a threaded female cap, opening at z = 0
// ============================================================
module female_cap(bore_r, outer_r, lead, starts, depth,
                  thread_width, engage_h, pitch, cap_h) {
    union() {
        // Outer shell with smooth bore
        difference() {
            cylinder(r = outer_r, h = cap_h);
            translate([0, 0, -0.01])
                cylinder(r = bore_r, h = cap_h + 0.02);
        }
        // Helical thread ridges -- offset by one pitch for lead-in
        translate([0, 0, pitch])
        thread_ridges(bore_r, lead, starts, depth,
                      thread_width, engage_h);
    }
}

// ============================================================
// Assembly
// ============================================================
difference() {
    union() {
        // -- Cap A -- opening faces -Z (bottom of adapter)
        female_cap(A_bore_r, A_outer_r, A_lead, A_starts, A_depth,
                   A_thread_width, A_engage_h, A_pitch, A_cap_h);

        // -- Connector cylinder
        translate([0, 0, A_cap_h])
            cylinder(r = conn_r, h = conn_h);

        // -- Cap B -- flipped so opening faces +Z (top)
        translate([0, 0, A_cap_h + conn_h + B_cap_h])
        rotate([180, 0, 0])
        female_cap(B_bore_r, B_outer_r, B_lead, B_starts, B_depth,
                   B_thread_width, B_engage_h, B_pitch, B_cap_h);
    }

    // -- Flow-through bore
    // Each cap already has its own bore; just bore the connector.
    translate([0, 0, A_cap_h - 0.01])
        cylinder(r = flow_r, h = conn_h + 0.02);
}
`;
}
